-- ОЧИЩЕННЯ БАЗИ ДАНИХ
-- Використовуємо CASCADE CONSTRAINTS для безпечного видалення зв'язків.
-- (При першому запуску помилки ORA-00942 є очікуваними та безпечними)
drop table tax_assessment cascade constraints;
drop table land_plot cascade constraints;
drop table employee cascade constraints;
drop table owner cascade constraints;
drop table land_type cascade constraints;
drop table street cascade constraints;
drop table settlement cascade constraints;
drop table postal_code cascade constraints;
drop table region cascade constraints;

--СТВОРЕННЯ ДОВІДКОВИХ ТАБЛИЦЬ

create table region (
   id_region   number generated by default as identity primary key,
   region_name varchar2(100) not null
);

create table postal_code (
   id_postal_code number generated by default as identity primary key,
   code           varchar2(20) not null
);

create table settlement (
   id_settlement   number generated by default as identity primary key,
   settlement_name varchar2(100) not null
);

create table street (
   id_street   number generated by default as identity primary key,
   street_name varchar2(100) not null
);

create table land_type (
   id_type  number generated by default as identity primary key,
   tax_rate number(10,2) not null
);

create table employee (
   id_employee number generated by default as identity primary key,
   full_name   varchar2(150) not null,
   position    varchar2(100)
);

-- СТВОРЕННЯ ОСНОВНИХ ТАБЛИЦЬ 

create table owner (
   id_owner        number generated by default as identity primary key,
   last_name       varchar2(50) not null,
   first_name      varchar2(50) not null,
   middle_name     varchar2(50),
   passport_number varchar2(20) unique,
   phone           varchar2(20),
   tax_code        varchar2(20) unique
);

create table land_plot (
   plot_number        varchar2(50) primary key,
   id_owner           number not null,
   id_type            number not null,
   length             number(10,2),
   width              number(10,2),
   id_region          number,
   id_postal_code     number,
   id_settlement      number,
   id_street          number,
   street_plot_number varchar2(20)
);

create table tax_assessment (
   id_assessment  number generated by default as identity primary key,
   plot_number    varchar2(50) not null,
   id_employee    number,
   date_formed    date not null,
   date_delivered date,
   date_paid      date,
   tax_amount     number(10,2) not null,
   status         varchar2(50) default 'Не сплачено',
   penalty        number(10,2) default 0
);

-- ВСТАНОВЛЕННЯ ЗВ'ЯЗКІВ (ЗОВНІШНІ КЛЮЧІ)

alter table land_plot
   add constraint fk_plot_region foreign key ( id_region )
      references region ( id_region );
alter table land_plot
   add constraint fk_plot_postal foreign key ( id_postal_code )
      references postal_code ( id_postal_code );
alter table land_plot
   add constraint fk_plot_settlement foreign key ( id_settlement )
      references settlement ( id_settlement );
alter table land_plot
   add constraint fk_plot_street foreign key ( id_street )
      references street ( id_street );
alter table land_plot
   add constraint fk_plot_type foreign key ( id_type )
      references land_type ( id_type );
alter table land_plot
   add constraint fk_plot_owner foreign key ( id_owner )
      references owner ( id_owner );

alter table tax_assessment
   add constraint fk_tax_plot foreign key ( plot_number )
      references land_plot ( plot_number );
alter table tax_assessment
   add constraint fk_tax_employee foreign key ( id_employee )
      references employee ( id_employee );

-- ДОДАВАННЯ ІНДЕКСІВ ДЛЯ ПОКРАЩЕННЯ ПРОДУКТИВНОСТІ

-- Індекси для зовнішніх ключів у таблиці Land_Plot
create index idx_land_plot_owner on
   land_plot (
      id_owner
   );
create index idx_land_plot_type on
   land_plot (
      id_type
   );
create index idx_land_plot_region on
   land_plot (
      id_region
   );
create index idx_land_plot_postal on
   land_plot (
      id_postal_code
   );
create index idx_land_plot_settlement on
   land_plot (
      id_settlement
   );
create index idx_land_plot_street on
   land_plot (
      id_street
   );

-- Індекси для зовнішніх ключів у таблиці Tax_Assessment
create index idx_tax_assessment_plot on
   tax_assessment (
      plot_number
   );
create index idx_tax_assessment_employee on
   tax_assessment (
      id_employee
   );

-- Індекси для часто запитуваних стовпців у таблиці Tax_Assessment
create index idx_tax_assessment_date_formed on
   tax_assessment (
      date_formed
   );
create index idx_tax_assessment_date_delivered on
   tax_assessment (
      date_delivered
   );
create index idx_tax_assessment_date_paid on
   tax_assessment (
      date_paid
   );
create index idx_tax_assessment_status on
   tax_assessment (
      status
   );

-- ДОДАВАННЯ КОМЕНТАРІВ ДО СТОВПЦІВ

comment on column region.region_name is
   'Назва області';
comment on column postal_code.code is
   'Поштовий індекс';
comment on column settlement.settlement_name is
   'Назва населеного пункту';
comment on column street.street_name is
   'Назва вулиці';
comment on column land_type.tax_rate is
   'грн/Га';
comment on column owner.last_name is
   'Прізвище';
comment on column owner.first_name is
   'Імʼя';
comment on column owner.middle_name is
   'По-батькові';
comment on column owner.passport_number is
   'Номер паспорту';
comment on column owner.phone is
   'Телефон';
comment on column owner.tax_code is
   'ІПН';
comment on column land_plot.plot_number is
   'Кадастровий номер';
comment on column land_plot.street_plot_number is
   'Номер ділянки в рамках вулиці';
comment on column tax_assessment.date_formed is
   'Дата формування';
comment on column tax_assessment.date_delivered is
   'Дата вручення';
comment on column tax_assessment.date_paid is
   'Дата сплати';
comment on column tax_assessment.status is
   'сплачено / не сплачено';
comment on column tax_assessment.penalty is
   'Пеня або Штраф за прострочення';